export const SET_CART = "SET_CART";

export const REMOVE_CART = "REMOVE_CART";
export const SET_PAYMENT = "SET_PAYMENT";
export const SET_PAYMENT_REQUEST = "SET_PAYMENT_REQUEST";
export const SET_PAYMENT_ERROR = "SET_PAYMENT_ERROR";

export const SET_ADDRESS = "SET_ADDRESS";
export const SET_ONE_ADDRESS = "SET_ONE_ADDRESS";
export const SET_ADDRESS_REQUEST = "SET_ADDRESS_REQUEST";
export const SET_ADDRESS_ERROR = "SET_ADDRESS_ERROR";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

export const SET_SHIPPING_ADDRESS = "SET_SHIPPING_ADDRESS";
export const SET_RECEIPT_ADDRESS = "SET_RECEIPT_ADDRESS";

export const SELECT_CARD = "SELECT_CARD";

export const SET_ORDER = "SET_ORDER";
export const SET_ORDER_REQUEST = "SET_ORDER_REQUEST";
export const SET_ORDER_ERROR = "SET_ORDER_ERROR";

export const CLEAR_CART = "CLEAR_CART";
