export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORIES_REQUEST = "SET_CATEGORIES_REQUEST";
export const SET_CATEGORIES_ERROR = "SET_CATEGORIES_ERROR";

export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_PRODUCT_LIST_REQUEST = "SET_PRODUCT_LIST_REQUEST";
export const SET_PRODUCT_LIST_ERROR = "SET_PRODUCT_LIST_ERROR";

export const SET_FETCH_STATE = "SET_FETCH_STATE";
export const SET_TOTAL = "SET_TOTAL";
export const SET_LIMIT = "SET_LIMIT";
export const SET_OFFSET = "SET_OFFSET";
export const SET_FILTER = "SET_FILTER";
